print("Getting to know you!")
print()
name = input("What's your name?: ")
food = input("What's your favorite food: ")
music = input("What's your favorite music? ")
live = input("Where do you live?: ")
print()
print("You are ", name, "and you love")
print(food, " so much that you want to eat that now")
print("You definitely enjoy listenning to", music)
print("You're going to a restaurant in ")
print(live, "where you live.")